Created folder structure, added the components and pages
Santhosh-BE/React_Training pull request #2
Opened 2024-08-26 12:26 UTC by Vigneshsubr

Created dummy components are Button, Label and Input then pages are SignUp, Login , Update and ListOfData

2024-08-26 12:43 UTC, Santhosh-BE commented
@Vigneshsubr  

1. create a proper components file 
2. folder structure need to beproper

2024-08-26 12:47 UTC, Santhosh-BE requested changes

2024-08-26 12:47 UTC, Santhosh-BE commented on react-api-integration/src/components/Buttton.jsx
Do not create empty files for components. Ensure each component file has a proper structure and content.

2024-08-26 12:47 UTC, Santhosh-BE commented on react-api-integration/src/components/Input.jsx
Do not create empty files for components. Ensure each component file has a proper structure and content.

2024-08-26 12:47 UTC, Santhosh-BE commented on react-api-integration/src/components/Label.jsx
Do not create empty files for components. Ensure each component file has a proper structure and content.

2024-08-27 05:27 UTC, Vigneshsubr commented on react-api-integration/src/components/Buttton.jsx
Now created the Folders as assets, utils  and redux folders

2024-08-27 05:28 UTC, Vigneshsubr commented on react-api-integration/src/components/Input.jsx
now solved anna

2024-08-27 05:28 UTC, Vigneshsubr commented on react-api-integration/src/components/Label.jsx
now solved

2024-08-27 05:29 UTC, merged